FROM golang:1.23-alpine

RUN apk add --no-cache curl git

RUN go install github.com/air-verse/air@v1.61.1
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

WORKDIR /app

COPY go.mod go.sum ./
COPY .air.toml ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
