// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type Artist struct {
	ID          string
	Name        string
	NameEn      sql.NullString
	NameJa      sql.NullString
	Description sql.NullString
	Tags        sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Instrument struct {
	ID          string
	Name        string
	Type        sql.NullString
	ArtistID    sql.NullString
	Description sql.NullString
	Tags        sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
