// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/v1/artist.proto

package proto_v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "rockstart/src/_generated/proto/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ArtistServiceName is the fully-qualified name of the ArtistService service.
	ArtistServiceName = "proto.v1.artist.ArtistService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ArtistServiceGetArtistsProcedure is the fully-qualified name of the ArtistService's GetArtists
	// RPC.
	ArtistServiceGetArtistsProcedure = "/proto.v1.artist.ArtistService/GetArtists"
)

// ArtistServiceClient is a client for the proto.v1.artist.ArtistService service.
type ArtistServiceClient interface {
	GetArtists(context.Context, *connect.Request[v1.GetArtistsRequest]) (*connect.Response[v1.GetArtistsResponse], error)
}

// NewArtistServiceClient constructs a client for the proto.v1.artist.ArtistService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArtistServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArtistServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	artistServiceMethods := v1.File_proto_v1_artist_proto.Services().ByName("ArtistService").Methods()
	return &artistServiceClient{
		getArtists: connect.NewClient[v1.GetArtistsRequest, v1.GetArtistsResponse](
			httpClient,
			baseURL+ArtistServiceGetArtistsProcedure,
			connect.WithSchema(artistServiceMethods.ByName("GetArtists")),
			connect.WithClientOptions(opts...),
		),
	}
}

// artistServiceClient implements ArtistServiceClient.
type artistServiceClient struct {
	getArtists *connect.Client[v1.GetArtistsRequest, v1.GetArtistsResponse]
}

// GetArtists calls proto.v1.artist.ArtistService.GetArtists.
func (c *artistServiceClient) GetArtists(ctx context.Context, req *connect.Request[v1.GetArtistsRequest]) (*connect.Response[v1.GetArtistsResponse], error) {
	return c.getArtists.CallUnary(ctx, req)
}

// ArtistServiceHandler is an implementation of the proto.v1.artist.ArtistService service.
type ArtistServiceHandler interface {
	GetArtists(context.Context, *connect.Request[v1.GetArtistsRequest]) (*connect.Response[v1.GetArtistsResponse], error)
}

// NewArtistServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArtistServiceHandler(svc ArtistServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	artistServiceMethods := v1.File_proto_v1_artist_proto.Services().ByName("ArtistService").Methods()
	artistServiceGetArtistsHandler := connect.NewUnaryHandler(
		ArtistServiceGetArtistsProcedure,
		svc.GetArtists,
		connect.WithSchema(artistServiceMethods.ByName("GetArtists")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.v1.artist.ArtistService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArtistServiceGetArtistsProcedure:
			artistServiceGetArtistsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArtistServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedArtistServiceHandler struct{}

func (UnimplementedArtistServiceHandler) GetArtists(context.Context, *connect.Request[v1.GetArtistsRequest]) (*connect.Response[v1.GetArtistsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.v1.artist.ArtistService.GetArtists is not implemented"))
}
