name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # Store your service account key in GitHub Secrets

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.IMAGE }}:latest \
            -f apps/backend/Dockerfile \
            ./apps/backend

      - name: Push Docker image
        run: |
          docker push ${{ secrets.IMAGE }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image ${{ secrets.IMAGE }}:latest \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --service-account ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}  # Store your service account email in GitHub Secrets

      - name: Clean up
        run: |
          docker logout gcr.io